version: '3.8'

networks:
  app-network:
    name: app-network  # Fixed network name

services:
  mssql:
    networks:
      - app-network
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'StrongP@ssw0rd!'
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

  jenkins:
    build:
      context: ./jenkins
      args:
        DOCKER_GID: ${DOCKER_GID}  # Pass host's Docker GID
    networks:
      - app-network
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  mssql_data:
  jenkins_home: