version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  mssql:
    networks:
      - app-network
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'StrongP@ssw0rd!'
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

  jenkins:
    networks:
      - app-network
    build: ./jenkins
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  liquibase:
    networks:
      - app-network
    build: ./liquibase
    container_name: liquibase
    volumes:
      - ./changelogs:/liquibase/changelogs
    command: >
      bash -c "while ! nc -z mssql 1433; do sleep 2; done;
      liquibase --changeLogFile=db.changelog-master.xml
      --url='jdbc:sqlserver://mssql:1433;databaseName=student_management'
      --username=sa
      --password=StrongP@ssw0rd!
      --driver=com.microsoft.sqlserver.jdbc.SQLServerDriver
      update"

volumes:
  mssql_data:
  jenkins_home:
